company_tickers = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "GOOGL": "Google",
    "META": "Meta",
    "TSLA": "Tesla",
    "NVDA": "NVIDIA",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart",
    "PG": "Procter & Gamble",
    "UNH": "UnitedHealth",
    "MA": "Mastercard",
    "HD": "Home Depot",
    "BAC": "Bank of America",
    "DIS": "Disney",
    "ADBE": "Adobe",
    "NFLX": "Netflix",
    "CRM": "Salesforce",
    "CMCSA": "Comcast",
    "XOM": "Exxon Mobil",
    "VZ": "Verizon",
    "COST": "Costco",
    "INTC": "Intel",
    "T": "AT&T",
    "PFE": "Pfizer",
    "CSCO": "Cisco",
    "KO": "Coca-Cola",
    "ABT": "Abbott",
    "PEP": "PepsiCo",
    "MRK": "Merck",
    "ABBV": "AbbVie",
    "ORCL": "Oracle",
    "TMO": "Thermo Fisher",
    "NKE": "Nike",
    "AVGO": "Broadcom",
    "MCD": "McDonald's",
    "LLY": "Eli Lilly",
    "NEE": "NextEra Energy",
    "DHR": "Danaher",
    "MDT": "Medtronic",
    "UNP": "Union Pacific",
    "TXN": "Texas Instruments",
    "BMY": "Bristol-Myers Squibb",
    "LIN": "Linde",
    "PM": "Philip Morris",
    "QCOM": "Qualcomm",
    "AMT": "American Tower",
    "HON": "Honeywell",
    "IBM": "IBM",
    "RTX": "Raytheon",
    "BA": "Boeing",
    "CVX": "Chevron",
    "SBUX": "Starbucks",
    "AMGN": "Amgen",
    "GE": "General Electric",
    "CAT": "Caterpillar",
    "MMM": "3M",
    "GS": "Goldman Sachs",
    "BLK": "BlackRock",
    "ISRG": "Intuitive Surgical",
    "AXP": "American Express",
    "LOW": "Lowe's",
    "DE": "John Deere",
    "BKNG": "Booking Holdings",
    "CHTR": "Charter Communications",
    "INTU": "Intuit",
    "MDLZ": "Mondelez",
    "TGT": "Target",
    "SPGI": "S&P Global",
    "ZTS": "Zoetis",
    "CI": "Cigna",
    "PYPL": "PayPal",
    "SYK": "Stryker",
    "PLD": "Prologis",
    "GILD": "Gilead Sciences",
    "ANTM": "Anthem",
    "ADI": "Analog Devices",
    "CCI": "Crown Castle",
    "MMC": "Marsh & McLennan",
    "CME": "CME Group",
    "COF": "Capital One",
    "USB": "U.S. Bank",
    "TFC": "Truist Financial",
    "GM": "General Motors",
    "EQIX": "Equinix",
    "DUK": "Duke Energy",
    "SCHW": "Charles Schwab",
    "SO": "Southern Company",
    "PNC": "PNC Financial",
    "CSX": "CSX",
    "ICE": "Intercontinental Exchange",
    "ATVI": "Activision Blizzard",
    "D": "Dominion Energy",
    "VRTX": "Vertex Pharmaceuticals",
    "EOG": "EOG Resources",
    "EL": "Estée Lauder",
    "ITW": "Illinois Tool Works",
    "NSC": "Norfolk Southern",
    "FISV": "Fiserv",
    "EW": "Edwards Lifesciences",
    "HUM": "Humana",
    "ADP": "ADP",
    "SHW": "Sherwin-Williams",
    "GD": "General Dynamics",
}
